/**
 * NOTE:
 * - Keep this file small and stable.
 * - Put view-model types in feature folders if they are UI-specific.
 */

/**
 * Trip Planner Database Types
 * Auto-generated from Supabase schema
 *
 * @see supabase/migrations/20260119000000_initial_schema.sql
 */

/**
 * AUTO-GENERATED. DO NOT EDIT MANUALLY.
 * Generated by Supabase CLI:
 *   supabase gen types typescript --project-id <id> --schema public > src/types/database.types.ts
 *
 * This file is used for:
 * - TS type safety (when using TS)
 * - reference for table/column shape (even in JS)
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          username: string;
          full_name: string | null;
          avatar_url: string | null;
          bio: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          username: string;
          full_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          username?: string;
          full_name?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      trips: {
        Row: {
          id: string;
          title: string;
          summary: string | null;
          start_date: string;
          end_date: string;
          cover_image_url: string | null;
          visibility: 'public' | 'unlisted' | 'private';
          created_by: string;
          created_at: string;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          title: string;
          summary?: string | null;
          start_date: string;
          end_date: string;
          cover_image_url?: string | null;
          visibility?: 'public' | 'unlisted' | 'private';
          created_by: string;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          title?: string;
          summary?: string | null;
          start_date?: string;
          end_date?: string;
          cover_image_url?: string | null;
          visibility?: 'public' | 'unlisted' | 'private';
          created_by?: string;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'trips_created_by_fkey';
            columns: ['created_by'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'trips_updated_by_fkey';
            columns: ['updated_by'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      trip_members: {
        Row: {
          id: string;
          trip_id: string;
          user_id: string;
          role: 'owner' | 'editor';
          joined_at: string;
        };
        Insert: {
          id?: string;
          trip_id: string;
          user_id: string;
          role: 'owner' | 'editor';
          joined_at?: string;
        };
        Update: {
          id?: string;
          trip_id?: string;
          user_id?: string;
          role?: 'owner' | 'editor';
          joined_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'trip_members_trip_id_fkey';
            columns: ['trip_id'];
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'trip_members_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      places: {
        Row: {
          id: string;
          provider: string;
          provider_place_id: string;
          name: string;
          category: string | null;
          address: string | null;
          road_address: string | null;
          phone: string | null;
          latitude: number;
          longitude: number;
          raw_data: Json | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          provider: string;
          provider_place_id: string;
          name: string;
          category?: string | null;
          address?: string | null;
          road_address?: string | null;
          phone?: string | null;
          latitude: number | string;
          longitude: number | string;
          raw_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          provider?: string;
          provider_place_id?: string;
          name?: string;
          category?: string | null;
          address?: string | null;
          road_address?: string | null;
          phone?: string | null;
          latitude?: number | string;
          longitude?: number | string;
          raw_data?: Json | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [];
      };
      trip_days: {
        Row: {
          id: string;
          trip_id: string;
          date: string;
          notes: string | null;
          created_at: string;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          trip_id: string;
          date: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          trip_id?: string;
          date?: string;
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'trip_days_trip_id_fkey';
            columns: ['trip_id'];
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'trip_days_updated_by_fkey';
            columns: ['updated_by'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      schedule_items: {
        Row: {
          id: string;
          trip_day_id: string;
          place_id: string;
          time: string | null;
          duration_minutes: number | null;
          notes: string | null;
          order_index: number;
          created_at: string;
          updated_at: string;
          updated_by: string | null;
        };
        Insert: {
          id?: string;
          trip_day_id: string;
          place_id: string;
          time?: string | null;
          duration_minutes?: number | null;
          notes?: string | null;
          order_index?: number;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Update: {
          id?: string;
          trip_day_id?: string;
          place_id?: string;
          time?: string | null;
          duration_minutes?: number | null;
          notes?: string | null;
          order_index?: number;
          created_at?: string;
          updated_at?: string;
          updated_by?: string | null;
        };
        Relationships: [
          {
            foreignKeyName: 'schedule_items_trip_day_id_fkey';
            columns: ['trip_day_id'];
            referencedRelation: 'trip_days';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'schedule_items_place_id_fkey';
            columns: ['place_id'];
            referencedRelation: 'places';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'schedule_items_updated_by_fkey';
            columns: ['updated_by'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      themes: {
        Row: {
          id: string;
          name: string;
          slug: string;
          icon: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          icon?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          icon?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      regions: {
        Row: {
          id: string;
          name: string;
          slug: string;
          country_code: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          country_code?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          country_code?: string | null;
          created_at?: string;
        };
        Relationships: [];
      };
      trip_themes: {
        Row: {
          trip_id: string;
          theme_id: string;
          created_at: string;
        };
        Insert: {
          trip_id: string;
          theme_id: string;
          created_at?: string;
        };
        Update: {
          trip_id?: string;
          theme_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'trip_themes_trip_id_fkey';
            columns: ['trip_id'];
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'trip_themes_theme_id_fkey';
            columns: ['theme_id'];
            referencedRelation: 'themes';
            referencedColumns: ['id'];
          },
        ];
      };
      trip_regions: {
        Row: {
          trip_id: string;
          region_id: string;
          created_at: string;
        };
        Insert: {
          trip_id: string;
          region_id: string;
          created_at?: string;
        };
        Update: {
          trip_id?: string;
          region_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'trip_regions_trip_id_fkey';
            columns: ['trip_id'];
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'trip_regions_region_id_fkey';
            columns: ['region_id'];
            referencedRelation: 'regions';
            referencedColumns: ['id'];
          },
        ];
      };
      trip_likes: {
        Row: {
          trip_id: string;
          user_id: string;
          created_at: string;
        };
        Insert: {
          trip_id: string;
          user_id: string;
          created_at?: string;
        };
        Update: {
          trip_id?: string;
          user_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'trip_likes_trip_id_fkey';
            columns: ['trip_id'];
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'trip_likes_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      trip_bookmarks: {
        Row: {
          trip_id: string;
          user_id: string;
          created_at: string;
        };
        Insert: {
          trip_id: string;
          user_id: string;
          created_at?: string;
        };
        Update: {
          trip_id?: string;
          user_id?: string;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'trip_bookmarks_trip_id_fkey';
            columns: ['trip_id'];
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'trip_bookmarks_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      reviews: {
        Row: {
          id: string;
          author_id: string;
          target_type: 'trip' | 'place';
          trip_id: string | null;
          place_id: string | null;
          rating: number;
          content: string | null;
          visited_on: string | null;
          photo_urls: string[] | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          author_id: string;
          target_type: 'trip' | 'place';
          trip_id?: string | null;
          place_id?: string | null;
          rating: number;
          content?: string | null;
          visited_on?: string | null;
          photo_urls?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          author_id?: string;
          target_type?: 'trip' | 'place';
          trip_id?: string | null;
          place_id?: string | null;
          rating?: number;
          content?: string | null;
          visited_on?: string | null;
          photo_urls?: string[] | null;
          created_at?: string;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'reviews_author_id_fkey';
            columns: ['author_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'reviews_trip_id_fkey';
            columns: ['trip_id'];
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'reviews_place_id_fkey';
            columns: ['place_id'];
            referencedRelation: 'places';
            referencedColumns: ['id'];
          },
        ];
      };
      trip_invite_links: {
        Row: {
          id: string;
          trip_id: string;
          token: string;
          created_by: string;
          expires_at: string | null;
          max_uses: number | null;
          use_count: number;
          created_at: string;
        };
        Insert: {
          id?: string;
          trip_id: string;
          token?: string;
          created_by: string;
          expires_at?: string | null;
          max_uses?: number | null;
          use_count?: number;
          created_at?: string;
        };
        Update: {
          id?: string;
          trip_id?: string;
          token?: string;
          created_by?: string;
          expires_at?: string | null;
          max_uses?: number | null;
          use_count?: number;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'trip_invite_links_trip_id_fkey';
            columns: ['trip_id'];
            referencedRelation: 'trips';
            referencedColumns: ['id'];
          },
          {
            foreignKeyName: 'trip_invite_links_created_by_fkey';
            columns: ['created_by'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      ai_query_suggestions: {
        Row: {
          id: string;
          user_id: string | null;
          original_query: string;
          normalized_query: string;
          suggestions: Json | null;
          model: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          original_query: string;
          normalized_query: string;
          suggestions?: Json | null;
          model?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          original_query?: string;
          normalized_query?: string;
          suggestions?: Json | null;
          model?: string | null;
          created_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'ai_query_suggestions_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
      rate_limits: {
        Row: {
          id: string;
          user_id: string | null;
          operation: string;
          count: number;
          window_start: string;
        };
        Insert: {
          id?: string;
          user_id?: string | null;
          operation: string;
          count?: number;
          window_start?: string;
        };
        Update: {
          id?: string;
          user_id?: string | null;
          operation?: string;
          count?: number;
          window_start?: string;
        };
        Relationships: [
          {
            foreignKeyName: 'rate_limits_user_id_fkey';
            columns: ['user_id'];
            referencedRelation: 'profiles';
            referencedColumns: ['id'];
          },
        ];
      };
    };
    Views: {};
    Functions: {
      can_edit_trip: {
        Args: { p_trip_id: string };
        Returns: boolean;
      };
      can_view_trip: {
        Args: { p_trip_id: string };
        Returns: boolean;
      };
      get_trip_visibility: {
        Args: { p_trip_id: string };
        Returns: string;
      };
      is_trip_member: {
        Args: { p_trip_id: string };
        Returns: boolean;
      };
      is_trip_owner: {
        Args: { p_trip_id: string };
        Returns: boolean;
      };
    };
    Enums: {};
    CompositeTypes: {};
  };
};
